# Generated by Django 4.2.7 on 2023-12-05 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True, verbose_name='Toidu kategooria nimi:')),
                ('category_sort_id', models.PositiveIntegerField(verbose_name='Toidu kategooria number:')),
            ],
            options={
                'verbose_name_plural': 'category_names',
                'ordering': ['category_sort_id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('theme', models.CharField(blank=True, max_length=30, null=True)),
                ('recommends', models.CharField(blank=True, max_length=30, null=True)),
                ('prepared', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'menu',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.category')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.menu')),
            ],
            options={
                'ordering': ['-date', 'category_id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('full_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('half_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('show_in_menu', models.BooleanField(default=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_fooditem', to='app_admin.foodmenu')),
            ],
            options={
                'ordering': ['menu'],
            },
        ),
    ]
