# Generated by Django 4.2.7 on 2024-01-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(max_length=150),
        ),
    ]
