# Generated by Django 4.2.7 on 2024-01-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0003_alter_menu_prepared_alter_menu_recommends_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
