# Generated by Django 4.2.7 on 2024-03-07 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_alter_category_category_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodmenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.category'),
        ),
    ]
